const CartActionTypes = {
    ADD_ITEM: 'ADD_ITEM',
    CLEAR_ITEM_FROM_CART: 'CLEAR_ITEM_FROM_CART',
    REMOVE_ITEM: 'REMOVE_ITEM',
    INCREASE_TOTAL_CART: 'INCREASE_TOTAL_CART',
    DECREASE_TOTAL_CART: 'DECREASE_TOTAL_CART'
}

export default CartActionTypes